env: prod

paths:
  employees: s3://oil-list-1002/Bronze_Layer/employee_records.csv
  sales: s3://oil-list-1002/Bronze_Layer/new_sales.csv
  cities: s3://oil-list-1002/Bronze_Layer/cities.csv
  water_mark: s3://oil-list-1002/Git-Code/logs/watermark/watermark.json

output:
  fact_orders_360: s3://oil-list-1002/Git-Code/fact_orders_360/
  dim_customer_order_metrics: s3://oil-list-1002/Git-Code/dim_customer_order_metrics/
  customer_scd_type_2: s3://oil-list-1002/Git-Code/scd_type_2/customer/
  product_scd_type_2: s3://oil-list-1002/Git-Code/scd_type_2/product/
  seller_scd_type_2: s3://oil-list-1002/Git-Code/scd_type_2/seller/

spark:
  shuffle_partitions: 50